### ISSUE TITLE
cannot import name 'BaseItem' 

### ISSUE THREAD

**Issue by namdroid** [Gerapy/Gerapy#311]
i get this error: 
```
    from scrapy.item import BaseItem
ImportError: cannot import name 'BaseItem' from 'scrapy.item' (/.virtualenvs/pyglobalenv/lib/python3.12/site-packages/scrapy/item.py)
```

**Comment by ajitmp** [comment]
I think it is Scrapy version issue, in newer version of scrapy BaseItem is replaced with just Item. The virtualenv is using Python3.12 which may caused a latest version of Scrapy while the Gerapy last update is in 2023 so may be not supporting latest version of scrapy.

**Comment by ajitmp** [comment]
As a quick solution, create a new virtual environment with lower python version like 3.10 or 3.11 and then install Gerapy again.  or long term solution, update the Gerapy code for using latest version of scrapy (basically, lots of changes may be required.)

**Comment by Germey** [comment]
Fixed in #321 (merged to `master`).

`gerapy/server/core/parser.py` now imports `BaseItem` with a fallback to `scrapy.Item`, so it works on Scrapy ≥ 2.6 (where `scrapy.item.BaseItem` was removed) as well as on older versions.

Verified: `import gerapy.server.core.parser` succeeds on Scrapy 2.16, and `gerapy` installs/migrates cleanly.
